name: Daily Market AI Agent

on:
  schedule:
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

jobs:
  run-ai-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests google-generativeai python-dotenv

      - name: Run the AI Script
        env:
          FINANCE_API_KEY: ${{ secrets.FINANCE_API_KEY }}
          SENTIMENT_API_KEY: ${{ secrets.SENTIMENT_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python sentiment_tracker.py
          
      - name: Upload the AI Report
        uses: actions/upload-artifact@v4
        with:
          name: Daily-Business-Report
          path: ai_business_report.txt

      - name: Send Report to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: curl --max-time 10 -F "payload_json={\"content\":\"🚀 **Daily AI Quant Report is Ready!**\"}" -F "file=@ai_business_report.txt" $DISCORD_WEBHOOK